# Generated by Django 6.0.7 on 2026-08-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='backup_database',
        ),
        migrations.AddField(
            model_name='settings',
            name='backup_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='backup_provider',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='settings',
            name='currency',
            field=models.CharField(default='GHS', max_length=3),
        ),
        migrations.AlterField(
            model_name='settings',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to='store_logos/'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='timezone',
            field=models.CharField(default='Africa/Accra', max_length=50),
        ),
    ]
